# docker-compose
version: '3.8'  # It's recommended to use a string for the version

services:
  accessibility_app:
    container_name: accessibility_app
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./host_data:/app/data
    environment:
      - NAME=World
      - TZ=Europe/Berlin
      - DOCKER_ENV=true  #new
    restart: unless-stopped