# pyproject.toml  (root of repo)
[tool.ruff]
line-length = 100
target-version = "py312"
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "I",   # isort
  "B",   # bugbear
  "UP",  # pyupgrade
  "C4"   # comprehensions
]
ignore = ["E501"]          # long lines, adjust if you want strict
exclude = ["ally_env", ".venv"]